messages: # Сообщения.
  help: "&#00C1FFNExperience помощь:\n/nexp <кол-во|max> - конвертировать опыт.\n/nexp reload - перезагрузить конфиг."
  no-permission: "&#FF0000У вас нет прав на это."
  invalid-arg: "&#FF0000Неверный аргумент."
  not-enough-exp: "&#FF0000У вас недостаточно опыта."
  success: "&#08FB18Вы успешно конвертировали опыт."
  received-exp: "&#08FB18Вы получили &#00C1FF{amount} &#08FB18уровней опыта."
  config-reloaded: "&#08FB18Конфиг перезагружен." # Новое сообщение

bottle: # Предмет. {amount} - опыт который хранится в нём.
  name: "&fБутылка с &#00C1FF{amount} &fопытом" # Название предмета.
  lore: "&7Внутри &#00C1FF{amount} &7опыта." # Описание предмета.
